### ISSUE TITLE
Liquid-generated text is not scanned

### ISSUE THREAD

**Issue by xplosionmind** [manunamz/jekyll-wikilinks#9]
I have several Liquid `{% for %}` loops which parse wikilinks, and, while by using the original plugin by Maxime Vaillancourt they are converted into HTML links, with this plugin they does not.

I am completely ignorant about how Ruby or the deeper structure of Jekyll work, but it seems like `jekyll-wikilinks` comes into play before Liquid is parsed, hence not scanning text which is generated by Liquid, therefore not seeing new wikikinks which might appear.

Does it make sense? I am available to provide further information, if needed!

Thanks a lot.

**Comment by manunamz** [comment]
I'm not entirely sure what you mean by "I have several Liquid `{% for %}` loops which parse wikilinks".  Could you post a small example for me? 🙂

**Comment by xplosionmind** [comment]
Of course. For example, in every page of my website I add in the front matter some todos related to the page, like this:

```
---
todo:
  - 'add a description'
  - 'fix issue x'
  - 'merge this page with [[Page]]'
---
```

Then, I have a page where all of the todos are listed, so that I can keep track of the task I have to accomplish for every page:

```
<ul>
  {% for note in site.notes %}
    <li>[[{{ note.title }}]]<ul>
      {% for task in note.todo %}
         <li>{{ task }}</li>
      {% endfor %}
    </ul></li>
  {% endfor %}
</ul>
```

In both cases when the brackets are written by me in the loop, and when they are included in the todo list, they are not parsed and not transformed to HTML.

**Comment by manunamz** [comment]
Gotcha. Ok, so I decided to have the plugin only parse markdown files. The rationale is to view [[wikilinks]] as purely a markdown extension, and you typically don't expect markdown parsers to to parse html files (as far as I know?).  

Your use case reminds me of dynamic note-creation (see tiddlywiki's [macros](https://tiddlywiki.com/#Macros) or obsidian's [dataview plugin](https://github.com/blacksmithgu/obsidian-dataview)). I view these as a future feature that really depends on whenever and however that ends up being implemented (whether that's Obsidian or someone else who gets there first; I'm not counting Roam Research because that is not in markdown).

I realize this is not ideal as someone who can hack out more specifically what they want, but I want to make the implementation as standards-friendly as possible. 

I will leave this ticket open for a stretch in case you or anyone else has more input with regard to this implementation decision though.

**Comment by xplosionmind** [comment]
> I decided to have the plugin only parse markdown files. The rationale is to view [[wikilinks]] as purely a markdown extension, and you typically don't expect markdown parsers to to parse html files (as far as I know?).

I agree. Nevertheless, the plugin should be working in HTML blocks, for example, in a file called `example.md`:
```
Welcome to this sample **note**.

<div class="blue box">
   You may find further information in [[Sample note two]]
</div>

*Continuation of the note*…
```
`[[Sample Note Two]]` should be parsed as a link in HTML. Even if the file is in Markdown, there is an HTML portion which `jekyll-wikilinks` should not ignore.

<br />
<br />

> Your use case reminds me of dynamic note-creation (see tiddlywiki's [macros](https://tiddlywiki.com/#Macros) or obsidian's [dataview plugin](https://github.com/blacksmithgu/obsidian-dataview)). I view these as a future feature that really depends on whenever and however that ends up being implemented

Ok, I understand this is a low-priority feature. Thank you very much anyways!

**Comment by manunamz** [comment]
Hmm...I am unable to reproduce this issue -- if I cut/paste...

```
<div class="blue box">
   You may find further information in [[Sample note two]]
</div>
```

...into a random note on my machine, it works (as long as the note isn't missing and the classes exist -- I tested it against a raw style attribute).

**Comment by manunamz** [comment]
Let me know if this is still a problem and to add any other details that might prove informative.

In the meantime, I added a few [tests](https://github.com/manunamz/jekyll-wikilinks/blob/main/spec/jekyll-wikilinks/feature_vanilla_spec.rb#L178) to illustrate that html in markdown files should be preserved, handled properly, and process an [[wikilinks]] that occur within the body of the html.

**Comment by xplosionmind** [comment]
> I'm kind of at a loss.

Me too. Let’s close this and focus on more important bugs and features.
